sudo: false
language: ruby
rvm:
- 2.0.0
addons:
  apt:
    packages:
    - jpegoptim
    - optipng
    - jpegtran
    - s3cmd
before_script:
- chmod +x ./_scripts/init.sh
- "./_scripts/init.sh"
- bundle exec jekyll build
- chmod +x ./_scripts/deploy.sh
script:
- "./_scripts/deploy.sh"
branches:
  only:
  - master
  - stage
notifications:
  hipchat:
    rooms:
      secure: OofFMw+3fPDkpf6Kdt6raw//ylHzTYWIBLI25WJx3vNVne/jYN0fxES0j+AnIwKAb5Y9hKudx8Sk9lBIB28P2qDC178vpSaWYX4XTiRJYjTCFzJXCdBUugzXnvVa83hD2JCAZGUsfmhUplFiWaMxa9pZuSUvz3DlUo8BKVLN3lJkJsnHq6LLNgut0iVFQlTdwindIUyDpVQnZwE2R8o3sY5+Z0iQa4fByVkonH3z1zGEcXylmg/VMQA92Y2xwXQV3E6qUoL/A/DxaRDXzQO9IoSRApiKmCmrp69N+pkmTUKZ8vkG5vwPAsgyy+0qoRnHliWoPSL7T6Bn3wWKurbundIg58Xte11Lil4Y/ZVQoU2B67Swc1O93DpZbXhfy6lITn5WD/bNlJkKpZgUtChPzQ2PqaBAEPUAMPP/bIN31HzxFJ0t3bo+ORedQQk37HJeBh/ZNLkzm3s8d9SbthKvtkxz/wIe6+MctID3kyUAIX7aZvbXjuqB2SXnUuNDmKiiDVn+rOg5Ehn9Tv04EaRDvC82a9Q01N4F/XMqZOirsHGEPnb8A93yDk3Q0PveOZalzxKMMsBLrEBxGLR5GAwUfuUiF3KJlFkGNLJRdk0oYr4D8u+n6GU1fvJh1WJZl1UpRKQhldK+UvpWqxB5DpPut39B3o0hVz+h4NpGYIvCYfo=
    template:
    - '%{repository_slug} - <a href="%{build_url}">Build %{build_number}</a> <a href="%{compare_url}">%{commit}</a>
      on %{branch} by %{author}: %{commit_message} - Travis result: %{message}'
    format: html
env:
  global:
    - secure: JERoW0WykiZrTEUQaeAvtXiky26VUPldWXLmTHjJjZ1eImI5r051C99iiNV0OCTFFu3phoYUZ8YmO7epvWQLo0PB0W3BYpN5CtwIs0bK2ND50ji0U7WRaXPg+XmnFpS9lsxoHmZhEGuuTejJl2Ip+y2CFoqcrSSgfDOGaCPhXZNMNRuzvItmQ1B32Fq5IQG+627duceBEgkaNT05eSARB9ACLL0gAC4JMjV1yP1jafpaWXiTGCrBH1xr+AM8EB9qAy8KUURfWN8iv8IrGaqsg7Dnf9I+jNIzzsT4GOdnjZKpN8/NZIRo5xGkFILRqeNdlPAceiQLg+jIaaMqkRpZd8M5y+iYc3Vqa0LUmNtC5mTq58T1IzKCJr7UN4pexfrMsqUwYoFdtS7sbmj4P/JGhp23I/4B6R4AW+ZDCzF6NFxyh1E5dmyA0vkSQ9nwscDD/GIwHFDNDDxeH91P+LS4uC6FUzK3fn1oLMf3QzcoBMvMeWwz6r+mouYH5kZnZTZXGnTSR7OHhtD5slyP8fzfYnv9cpyugJiSH/rmOU/rC1A6+jyq5hD92+yNz8jrCKmp7Ul2IhRosjEIpoPPc2zGxs96YBhKFPgWFMiGA/Bimg/PnVZH5PTFqzXYV5ELvoNkDxoREV0Nb7KW6hNNJOnWhjw1MMFp8wu5Y5j/6hblzSY=
    - secure: h/657fxNlyNjdhCLDLEufiGjNMzCBWlYlVvkCykHbTag8J0SFkfE9/G1Dp6NgjjPAoH9r9U1e7BsjSgddfJMVnbOThAahHoqmWBBN46kT/0bVb5iSwW9vY06yPJBemFGNx6lkGRJpNmjnjpOm5MiXUQlYwrW7A6+xiNU0RSxDQdB9Ag/tu7AQ3398JMmet7D7N7nszu+JtzNH2QWE0vOjpo6GAhKhF6SVtHDfoImgr7Wl4i5qOvV6rJBW6jTcBPa8jQkO4NWtHxpzPNuARhv8U0H6sRg8/FMdnh+RauXKYCnPCcQWIqbDn7JN2Gab4bbtOobMQ2a1BSjzzYMMuTLDaNBU5euieIFiM9dxiBC9jo0q4e6+Cf4EyESpfqT5w1aFxdMrWO52Xg480+vypGdx9QPI8WPOQycyUyaOl7f+9xNnltL3TFc84UahEy3kN4T0dC4DW3uqp3qYeAJ/X6+7shTmqgy1pNfd2yRdEIQn+W/t1H+37FDQfTwh3dtlFwjyLnETj3wheq1Ce0DZDA2bLSG32CJFyOspS4XUxFKqkhpZfP/TC4Xt24JNkfWcHT4xQ425k1Yk0H5SWja5B4eUxYpG2O/POi8sbNvqxBcv4w1HtCBs6I7yuLQ4bd+Pjozme2QFDGlOn4sklwOcvCCP1Xy/QP8UQb330+8/RRjSNA=
