sudo: false
language: ruby
rvm:
- 2.0.0
addons:
  apt:
    packages:
    - jpegoptim
    - optipng
    - s3cmd
before_script:
- chmod +x ./_scripts/init.sh
- "./_scripts/init.sh"
- bundle exec jekyll build
- chmod +x ./_scripts/deploy.sh
script:
- "./_scripts/deploy.sh"
branches:
  only:
  - master
  - stage
notifications:
  hipchat:
    rooms:
      secure: OofFMw+3fPDkpf6Kdt6raw//ylHzTYWIBLI25WJx3vNVne/jYN0fxES0j+AnIwKAb5Y9hKudx8Sk9lBIB28P2qDC178vpSaWYX4XTiRJYjTCFzJXCdBUugzXnvVa83hD2JCAZGUsfmhUplFiWaMxa9pZuSUvz3DlUo8BKVLN3lJkJsnHq6LLNgut0iVFQlTdwindIUyDpVQnZwE2R8o3sY5+Z0iQa4fByVkonH3z1zGEcXylmg/VMQA92Y2xwXQV3E6qUoL/A/DxaRDXzQO9IoSRApiKmCmrp69N+pkmTUKZ8vkG5vwPAsgyy+0qoRnHliWoPSL7T6Bn3wWKurbundIg58Xte11Lil4Y/ZVQoU2B67Swc1O93DpZbXhfy6lITn5WD/bNlJkKpZgUtChPzQ2PqaBAEPUAMPP/bIN31HzxFJ0t3bo+ORedQQk37HJeBh/ZNLkzm3s8d9SbthKvtkxz/wIe6+MctID3kyUAIX7aZvbXjuqB2SXnUuNDmKiiDVn+rOg5Ehn9Tv04EaRDvC82a9Q01N4F/XMqZOirsHGEPnb8A93yDk3Q0PveOZalzxKMMsBLrEBxGLR5GAwUfuUiF3KJlFkGNLJRdk0oYr4D8u+n6GU1fvJh1WJZl1UpRKQhldK+UvpWqxB5DpPut39B3o0hVz+h4NpGYIvCYfo=
    template:
    - '%{repository_slug} - <a href="%{build_url}">Build %{build_number}</a> <a href="%{compare_url}">%{commit}</a>
      on %{branch} by %{author}: %{commit_message} - Travis result: %{message}'
    format: html
env:
  global:
    - secure: kkVdnycZWLg3vgxvDo7BSgNTMGmue0nCe3AL1T0TSbn8NCQ7UmZkxQMtJNsBCYDEa2amRgQsJCFG+G5giDGaHml142tL2N9MzhDWjBDci/pHWzBOb7/bBvEklY4FuLSg1EZbeRn+/HzTN/8kj1zS6kJQ2Ysc6UBz7uhk0S1RKbTYru1GXdmjUTDSLutuJ0kufEJR6ERgQat50lM9aXmIX7Kmp/a8L1hrWFlgjERj8/0KolnksUz3xucbGSgsrirFTGpNamDoj3ht/J1YlRrtWbU5sjcopyjyWGBrJHDpYOoIzBvyWvLRGU0SXeDMXSEoEHYEaWTLi2g0wKRvyBG60wVhHd5iBARm9/0AoQcutjbnYDyM+3ed1OSkDrZx9xQ8jt6wLTYroxHCCk4XRTDfZOQTHPko6aQYRz4Yis1bGwABvuuzic71+tPcv+wwXEGm6Xk/3eULVL+UND90shYFN4bvJ/PxuWg4ZsHri748oxMoi2/P5/XZTiEq3V+GFFiAfLKBhGUnl6BZAMgvMhz4obyGGdr9RmASVcPPMlGBIs1xJNYtU4eoF8nE/K3XdFhJASm1NGHgU7DzlaYUDfJVouClnApOZ35RLOs3v1RVbEImQxGQZfvm1CLbzXhCvsQLuaiFlyf4yJk+oA4KmuHxh9DSj5sMlVubpb3n6khkF+U=
    - secure: KCbAXi7Y2xFZ1Iwv4RcR+dvRIJOlOWF18jUJUgj70Um+PAKl6Ob3ptgf1+BSGu5R7N6pfMafsxKpjla9dDgRcmtZZekVMbD3/6Ac4ZOylKpS0jinwiBZTPNEmZhS+V1XA8QWv9xt8YGydKSrcDOVwFAiiTPz9CeUEQuhYW9eHqHgVAK50L3rUlprwgOEglXH+V7O7EVD1N68+GTWimJPtc0JVEnzLNeZQ/EShK5YAwxvvp6OueaOXGD+NR8qaedZ6YMq4RFVsHEyMhnSBUb5y5Mb6BXVm1LT+btpdv5EJBjtlmcfjigxtSJ/lTQhAqdpkH02iIhqkvusdltvtpBYLmMx27DquZO5gdKnmH/a5jr2X3vcclWLhZphPy+AQWcNbdgMe5A3+sClPkTx6eLBQqMvYMx/gfuPYEqCGBer9rndgXETsDLV1PYJXWthcHddSdA+EQsKjdumR2M39OdbXAkB0Ad9XprWE9PpjvAkaeKYqZZgG6ttdxB0QyId2luTQC4lgJ4iYtrhh14S1c0/NxJSAqvXDvIC7cptfdB8bSSkUPx/omNVoOewWUJhQPhVBS+XUK1JfqbyL+CED39dbJEbuhD1qLQt1DNzGUIJHVnvog7ne3GGJRHA+ySFwc1T5DITUQcCAUneWSa1gc6GW/Hb7NMTaPzr+3jHsusmuFk=
