sudo: false
language: ruby
rvm:
- 2.0.0
addons:
  apt:
    packages:
    - jpegoptim
    - optipng
before_script:
- pip install --user s3cmd
- chmod +x ./_scripts/init.sh
- "./_scripts/init.sh"
- bundle exec jekyll build
- chmod +x ./_scripts/deploy.sh
script:
- "./_scripts/deploy.sh"
branches:
  only:
  - master
  - stage
notifications:
  hipchat:
    rooms:
      secure: OofFMw+3fPDkpf6Kdt6raw//ylHzTYWIBLI25WJx3vNVne/jYN0fxES0j+AnIwKAb5Y9hKudx8Sk9lBIB28P2qDC178vpSaWYX4XTiRJYjTCFzJXCdBUugzXnvVa83hD2JCAZGUsfmhUplFiWaMxa9pZuSUvz3DlUo8BKVLN3lJkJsnHq6LLNgut0iVFQlTdwindIUyDpVQnZwE2R8o3sY5+Z0iQa4fByVkonH3z1zGEcXylmg/VMQA92Y2xwXQV3E6qUoL/A/DxaRDXzQO9IoSRApiKmCmrp69N+pkmTUKZ8vkG5vwPAsgyy+0qoRnHliWoPSL7T6Bn3wWKurbundIg58Xte11Lil4Y/ZVQoU2B67Swc1O93DpZbXhfy6lITn5WD/bNlJkKpZgUtChPzQ2PqaBAEPUAMPP/bIN31HzxFJ0t3bo+ORedQQk37HJeBh/ZNLkzm3s8d9SbthKvtkxz/wIe6+MctID3kyUAIX7aZvbXjuqB2SXnUuNDmKiiDVn+rOg5Ehn9Tv04EaRDvC82a9Q01N4F/XMqZOirsHGEPnb8A93yDk3Q0PveOZalzxKMMsBLrEBxGLR5GAwUfuUiF3KJlFkGNLJRdk0oYr4D8u+n6GU1fvJh1WJZl1UpRKQhldK+UvpWqxB5DpPut39B3o0hVz+h4NpGYIvCYfo=
    template:
    - '%{repository_slug} - <a href="%{build_url}">Build %{build_number}</a> <a href="%{compare_url}">%{commit}</a>
      on %{branch} by %{author}: %{commit_message} - Travis result: %{message}'
    format: html
env:
  global:
    - secure: UyABzp+XPLZ7chTZimxjQGS+KVsek7+NXBtpU55Q+a0nWJ8eso3di9sqVy0b0hYSI9Ui+Q1qFdqMBA9eqrdnJSqka4/PrrWZLVwHRW3/0grSKIrYdl/OvoO/5/4GKfxRRcZTq4gzMlnmzTJgPlPgUPYDg0OAoX1VkWfVg+ziyJWPK1Iy5ODE/sRfsCQbaEv5ZNvsimrRaPm3Z+XrM5pgWoombBG+Ycbpcl0mKHP0ckBIP3LQ3NKd1P3F+zjxFW8IImwxCRWROR08I2HZoXSFhCIoklZgtlDG+TMjiBIh/belkgJ5uY0cQEBQhANtMlDcKuBh6A7V4y4x+1jOYXOm1VwUnRMkoMFmA/mz6FWOp0RxT9bwR2kHrOXaqUYFiVsebqg9OfkmxYxjCql4Ebc0Iq+WyXatHCkhwe0YH88k9mCWl+Vleb19ABsK1S7yGoqEgS4V86rvXImo2iu96ZH8GDhoXJOCXi1WQyJcElhYQTDUXtvj1OfOWlQY7JAOAW51G6WLDYKX1OdQclvLdTuFwHzmc5wmGf9jsAI1NanX731JGN9ulxCjG6ygKZ8hlcIdvsVGXw+nxTYtqc+4yP9dmx1YrsKQFM5gm2fAFPsPGd2HojCVkmOku6lbXQ1zylWZA44cufa3IWpM597CeCQJlvW3gtp+MdDP+/vQXAre52w=
    - secure: TzaaFApOR/y9DzjnuYicHh96dFbjYgseRgw3UsIQ+WFlBd1vjUtBwL9Tbx1+i7ji/CxDEhrTEV8lWo7EQOBdLuITL8heE+2lQfhYzPN6xsPWPPhjrMEpTNj8pR80sU4QJwMO420SbptyeERSGQ0Zyzq6WFvgzprqiT3ZQHK1/jQMYlkPPQizcunJ4c8j/7OE9wRYPpfw/dlIzs9ReHcZFj8CLsUPc79Xdyj5EiMvYbAhBvRpvVxEKdkfFaHg4kq0gJ+g3D3V2Q6nj9pTP7qvrGLD/R6aZpVRWziEvI77OJjJrqoVVvz44s7d7Z7L1IZ1rNB3YUQRk0PMpcybbCJtJZCQ5ElMEml0P8nnCdqxASfr1PKkPllVPStGgOCM6sE61OPiBkKyG89sRCX+9BYveB33scjnx+FamSNJWZiyWUYpflYeQcWvYeQsM+mKjLoHzDPgQO4RK1ge+MvR9gEmb3YeQ4ZCt2eYMwFYl9t7A6vIci7+/QpcI0uxepcmyADYCK5VD68a9B68EZ2Fe2OLaenjB90M72TR7yCDY/N8xhSaLMb/FWTH7MUxoihjY+5fc4ShMXMti3Q4PgjTJS0m1bQoISRWVvCv4Mn83IZM6BVsxmrYdYa/GpR56gjXWuXM9vC8fN/idK6CEJEyDCMxP3NKyglYfjn4HjNmNt26gk0=
