sudo: false
language: ruby
rvm:
- 2.0.0
before_script:
- bundle exec jekyll build
script:
- "./_scripts/deploy.sh"
branches:
  only:
  - master
  - stage
notifications:
  hipchat:
    rooms:
      secure: E3zlkBhiqa162aZz1gTTj9CaM5XMjWycPLopxetgtKA1TBVaJ0wcS+E0DKl+gV1IyRwn9X/TSYN85CzJe3iwfEzxKu79EPayV1QtaUOQmrJcs+hdDqO/du3g68W+lNK/GDi0vEasCRnjKA8qAAtwSfxFsN1K7Nxoypjlva+3B39XUCD/Oy42nmSd1eR5kPmU1qT9lQm9Zfuh4EwIBCASrPxUTZCLs5ZAPSDoAzITviGOWRh+Pw9CnfxUQ9KpSCfUXTjyu1earsZEmTn92PrMPnMiSxYf310kk9Q/X2sKeZZ9U89346nsqt8S0RxL/FST5t4y8yEHiEvlATJLjfLUSnj36Yxp2DHDdOd/L8+uCuUsAr7+Q48FvsBEayuOLtHgQpnQ/YAjisW2sr7hsoQaCFWCdNtrKy2L1UcSMuZK3s+rx5lPWuYL4fPKyNWeCYogoLmGzMV3klWjmiaVs3u4EdadHbQcCO7QB0J8Hm0sUmiO+6PFGGbxOwB6TtWCmaFNDdtoPn5+bA+jK7CrP71ttGXHE00ERsg1jk9/Mjfdmpqry/XJ1PWCd57eTbR8aPcoTSVzol8qxrIbnBGrAE0CbyNHUF1Psu75ci4cy8PumVQwujru6K9gk5i3lGv+d7N/f+8iHGS+AQI5HNafwQNtdpFtL3jikB80KewAE2Nqcl4=
    template:
    - '%{repository_slug} - <a href="%{build_url}">Build %{build_number}</a> <a href="%{compare_url}">%{commit}</a>
      on %{branch} by %{author}: %{commit_message} - Travis result: %{message}'
    format: html
env:
  - secure: JERoW0WykiZrTEUQaeAvtXiky26VUPldWXLmTHjJjZ1eImI5r051C99iiNV0OCTFFu3phoYUZ8YmO7epvWQLo0PB0W3BYpN5CtwIs0bK2ND50ji0U7WRaXPg+XmnFpS9lsxoHmZhEGuuTejJl2Ip+y2CFoqcrSSgfDOGaCPhXZNMNRuzvItmQ1B32Fq5IQG+627duceBEgkaNT05eSARB9ACLL0gAC4JMjV1yP1jafpaWXiTGCrBH1xr+AM8EB9qAy8KUURfWN8iv8IrGaqsg7Dnf9I+jNIzzsT4GOdnjZKpN8/NZIRo5xGkFILRqeNdlPAceiQLg+jIaaMqkRpZd8M5y+iYc3Vqa0LUmNtC5mTq58T1IzKCJr7UN4pexfrMsqUwYoFdtS7sbmj4P/JGhp23I/4B6R4AW+ZDCzF6NFxyh1E5dmyA0vkSQ9nwscDD/GIwHFDNDDxeH91P+LS4uC6FUzK3fn1oLMf3QzcoBMvMeWwz6r+mouYH5kZnZTZXGnTSR7OHhtD5slyP8fzfYnv9cpyugJiSH/rmOU/rC1A6+jyq5hD92+yNz8jrCKmp7Ul2IhRosjEIpoPPc2zGxs96YBhKFPgWFMiGA/Bimg/PnVZH5PTFqzXYV5ELvoNkDxoREV0Nb7KW6hNNJOnWhjw1MMFp8wu5Y5j/6hblzSY=
  - secure: h/657fxNlyNjdhCLDLEufiGjNMzCBWlYlVvkCykHbTag8J0SFkfE9/G1Dp6NgjjPAoH9r9U1e7BsjSgddfJMVnbOThAahHoqmWBBN46kT/0bVb5iSwW9vY06yPJBemFGNx6lkGRJpNmjnjpOm5MiXUQlYwrW7A6+xiNU0RSxDQdB9Ag/tu7AQ3398JMmet7D7N7nszu+JtzNH2QWE0vOjpo6GAhKhF6SVtHDfoImgr7Wl4i5qOvV6rJBW6jTcBPa8jQkO4NWtHxpzPNuARhv8U0H6sRg8/FMdnh+RauXKYCnPCcQWIqbDn7JN2Gab4bbtOobMQ2a1BSjzzYMMuTLDaNBU5euieIFiM9dxiBC9jo0q4e6+Cf4EyESpfqT5w1aFxdMrWO52Xg480+vypGdx9QPI8WPOQycyUyaOl7f+9xNnltL3TFc84UahEy3kN4T0dC4DW3uqp3qYeAJ/X6+7shTmqgy1pNfd2yRdEIQn+W/t1H+37FDQfTwh3dtlFwjyLnETj3wheq1Ce0DZDA2bLSG32CJFyOspS4XUxFKqkhpZfP/TC4Xt24JNkfWcHT4xQ425k1Yk0H5SWja5B4eUxYpG2O/POi8sbNvqxBcv4w1HtCBs6I7yuLQ4bd+Pjozme2QFDGlOn4sklwOcvCCP1Xy/QP8UQb330+8/RRjSNA=
